# Generated by Django 6.0.3 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('counselor', 'Counselor'), ('emergency_operator', 'Emergency Operator')], default='patient', max_length=32),
        ),
    ]
