# Generated by Django 6.0.3 on 2026-03-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assistantaccessgrant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistantaccessgrant',
            new_name='core_assist_request_66d0f8_idx',
            old_name='core_assist_request_4814d6_idx',
        ),
    ]
