# Generated by Django 6.0.3 on 2026-03-28 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_assist_request_4814d6_idx_core_assist_request_66d0f8_idx'),
        ('hospital', '0012_patientfeedback_staff_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('direct', 'Direct'), ('team', 'Team')], default='direct', max_length=16)),
                ('purpose', models.CharField(choices=[('general_collaboration', 'General collaboration'), ('care_coordination', 'Care coordination'), ('rapid_recovery', 'Rapid recovery'), ('shift_handover', 'Shift handover'), ('lab_review', 'Lab review'), ('pharmacy_sync', 'Pharmacy synchronization'), ('surgery_prep', 'Surgery preparation'), ('emergency_response', 'Emergency response'), ('discharge_planning', 'Discharge planning')], default='general_collaboration', max_length=32)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(blank=True, max_length=16, unique=True)),
                ('assistant_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_conversations', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_conversations', to='hospital.hospital')),
                ('linked_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_conversations', to='hospital.patient')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.staffconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_label', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.staffconversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffconversation',
            index=models.Index(fields=['hospital', 'kind', 'is_active'], name='core_staffc_hospita_ea0854_idx'),
        ),
        migrations.AddIndex(
            model_name='staffconversation',
            index=models.Index(fields=['last_message_at'], name='core_staffc_last_me_172e32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffconversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='staffmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='core_staffm_convers_b8c4b7_idx'),
        ),
    ]
