# Generated by Django 6.0.3 on 2026-04-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_email_verification_failed_limits'),
        ('hospital', '0016_documentcategory_bed_last_cleaned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_hospital_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_users', to='hospital.hospitalinvitation'),
        ),
    ]
