# Generated by Django 6.0.3 on 2026-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcheck',
            name='intensity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='onset_summary',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='progression',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='structured_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
