# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_ward_doctor_department_patient_gender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, unique=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="HospitalAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("admin", "Admin"), ("doctor", "Doctor"), ("nurse", "Nurse"), ("receptionist", "Receptionist"), ("lab_technician", "Lab Technician"), ("pharmacist", "Pharmacist"), ("counselor", "Counselor")], max_length=30)),
                ("can_switch", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accesses", to="hospital.hospital")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hospital_accesses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "hospital", "role")},
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="patients", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="doctors", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_profiles", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="ward",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wards", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="bed",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="beds", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="admission",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admissions", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="queueticket",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="queue_tickets", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="shifts", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="certification",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="certifications", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vitals", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="labtestrequest",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lab_requests", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appointments", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="medical_records", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="billing",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billings", to="hospital.hospital"),
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="hospital",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visits", to="hospital.hospital"),
        ),
    ]
