# Generated by Django 6.0.3 on 2026-03-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_owner_alter_hospitalaccess_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('icd10_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for matching.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_rooms', to='hospital.hospital')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_rooms', to='hospital.ward')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('hospital', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(blank=True, max_length=180)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('diagnosed_at', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_links', to='hospital.conditioncatalog')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_records', to='hospital.hospital')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_links', to='hospital.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_records', to='hospital.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_records', to='hospital.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'is_active', 'severity'], name='hospital_pa_hospita_b63c27_idx'), models.Index(fields=['hospital', 'condition_name'], name='hospital_pa_hospita_048a48_idx'), models.Index(fields=['patient', 'created_at'], name='hospital_pa_patient_8c95af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurgicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=180)),
                ('procedure_code', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(choices=[('elective', 'Elective'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='elective', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pre_op', 'Pre-op'), ('in_surgery', 'In Surgery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('anesthesia_type', models.CharField(blank=True, max_length=120)),
                ('pre_op_assessment', models.TextField(blank=True)),
                ('post_op_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_cases', to='hospital.hospital')),
                ('operating_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_cases', to='hospital.operatingroom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_cases', to='hospital.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgical_cases', to='hospital.doctor')),
            ],
            options={
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['hospital', 'status', 'scheduled_start'], name='hospital_su_hospita_a9ac69_idx'), models.Index(fields=['patient', 'scheduled_start'], name='hospital_su_patient_5659cb_idx')],
            },
        ),
    ]
