# Generated by Django 6.0.3 on 2026-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_conditioncatalog_operatingroom_patientcondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalaccess',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('counselor', 'Counselor'), ('emergency_operator', 'Emergency Operator'), ('patient', 'Patient')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('counselor', 'Counselor'), ('emergency_operator', 'Emergency Operator'), ('patient', 'Patient')], max_length=30),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pre_op', 'Pre-op'), ('in_surgery', 'In Surgery'), ('recovery', 'Recovery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
    ]
