# Generated by Django 6.0.3 on 2026-03-26 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospitalaccess_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('symptoms', models.TextField(blank=True)),
                ('current_state', models.TextField(blank=True)),
                ('triage_notes', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('lab_summary', models.TextField(blank=True)),
                ('pharmacy_instructions', models.TextField(blank=True)),
                ('severity_index', models.PositiveSmallIntegerField(default=0)),
                ('severity_band', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting_triage', 'Waiting triage'), ('triaged', 'Triaged'), ('waiting_doctor', 'Waiting doctor'), ('in_consultation', 'In consultation'), ('awaiting_lab', 'Awaiting lab'), ('lab_ready', 'Lab ready'), ('awaiting_pharmacy', 'Awaiting pharmacy'), ('admission_review', 'Admission review'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting_triage', max_length=30)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_encounter', to='hospital.admission')),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_encounters', to='hospital.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_encounters', to='hospital.hospital')),
                ('linked_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_encounter', to='hospital.appointment')),
                ('medical_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_encounter', to='hospital.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_encounters', to='hospital.patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_walk_ins', to=settings.AUTH_USER_MODEL)),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_walk_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_critical', '-severity_index', 'arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pharmacy_tasks', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_tasks', to='hospital.hospital')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_tasks', to='hospital.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_tasks', to='hospital.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pharmacy_tasks', to=settings.AUTH_USER_MODEL)),
                ('walk_in_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_tasks', to='hospital.walkinencounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='walk_in_encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='hospital.walkinencounter'),
        ),
        migrations.CreateModel(
            name='WalkInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_events', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hospital.walkinencounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walkinencounter',
            index=models.Index(fields=['hospital', 'status', 'is_critical', 'severity_index'], name='hospital_wa_hospita_c4be44_idx'),
        ),
        migrations.AddIndex(
            model_name='walkinencounter',
            index=models.Index(fields=['patient', 'arrived_at'], name='hospital_wa_patient_b0974f_idx'),
        ),
    ]
