# Generated by Django 6.0.3 on 2026-03-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_walkinencounter_pharmacytask_and_more'),
        ('telemedicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='hospital.admission'),
        ),
        migrations.AddField(
            model_name='billing',
            name='billing_type',
            field=models.CharField(choices=[('general', 'General'), ('walk_in_registration', 'Walk-in Registration'), ('walk_in_triage', 'Walk-in Triage'), ('consultation', 'Consultation'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('admission', 'Admission'), ('bed_transfer', 'Bed Transfer'), ('discharge', 'Discharge'), ('telemedicine', 'Telemedicine')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='billing',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='billing',
            name='lab_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='hospital.labtestrequest'),
        ),
        migrations.AddField(
            model_name='billing',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='hospital.medicalrecord'),
        ),
        migrations.AddField(
            model_name='billing',
            name='pharmacy_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='hospital.pharmacytask'),
        ),
        migrations.AddField(
            model_name='billing',
            name='video_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='telemedicine.videoconsultation'),
        ),
        migrations.AddField(
            model_name='billing',
            name='walk_in_encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='hospital.walkinencounter'),
        ),
    ]
