# Generated by Django 6.0.3 on 2026-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_hospitalaccess_left_at_hospitalaccess_left_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('past', 'Past'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pre_op', 'Pre-op'), ('in_surgery', 'In Surgery'), ('recovery', 'Recovery'), ('past', 'Past'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
    ]
