# Generated by Django 6.0.3 on 2026-03-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_appointment_status_alter_surgicalcase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deceased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_patient_deaths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_recorded_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_patient_deaths', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
