# Generated by Django 6.0.3 on 2026-04-21 12:26

from datetime import datetime

from django.db import migrations, models
from django.utils import timezone


def backfill_shift_datetimes(apps, schema_editor):
    ShiftAssignment = apps.get_model("hospital", "ShiftAssignment")
    current_tz = timezone.get_current_timezone()
    for assignment in ShiftAssignment.objects.all().iterator():
        if assignment.start_at and assignment.end_at:
            continue
        if not assignment.shift_date or not assignment.start_time or not assignment.end_time:
            continue
        start_at = timezone.make_aware(datetime.combine(assignment.shift_date, assignment.start_time), current_tz)
        end_at = timezone.make_aware(datetime.combine(assignment.shift_date, assignment.end_time), current_tz)
        assignment.start_at = start_at
        assignment.end_at = end_at
        assignment.save(update_fields=["start_at", "end_at"])


def reverse_backfill_shift_datetimes(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_hospitalinvitation_revocation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ['start_at', 'shift_date', 'start_time', 'id']},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_shift_datetimes, reverse_backfill_shift_datetimes),
    ]
